# Generated by Django 5.2.3 on 2025-06-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_landingpages", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="landingpage",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="landingpage",
            name="access_code",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
