# Generated by Django 5.2.3 on 2025-06-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="artist",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
