# Generated by Django 5.2.3 on 2025-06-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="icons/"),
        ),
    ]
