# Generated by Django 5.2.3 on 2025-06-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0002_alter_post_options_post_artist_post_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="f_posts.tag"
            ),
        ),
    ]
