# Generated by Django 5.2.3 on 2025-06-30 19:51

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0002_alter_tag_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                storage=cloudinary_storage.storage.MediaCloudinaryStorage(
                    resource_type="image"
                ),
                upload_to="icons/",
            ),
        ),
    ]
