# Generated by Django 5.2.3 on 2025-06-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-order", "name"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
