# Generated by Django 5.2.3 on 2025-06-30 21:59

import flicksta.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0003_alter_tag_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="image",
            field=models.FileField(
                blank=True,
                null=True,
                storage=flicksta.storages.IconStorage(),
                upload_to="",
            ),
        ),
    ]
