# Generated by Django 5.2.3 on 2025-06-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0004_alter_tag_options_tag_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="icons/"),
        ),
    ]
