# Generated by Django 5.2.3 on 2025-07-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f_posts', '0004_alter_post_url_alter_tag_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
