# Generated by Django 5.2.3 on 2025-06-28 17:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("f_posts", "0011_likedreply_reply_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
