# Generated by Django 5.2.3 on 2025-06-30 21:59

import flicksta.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("f_users", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=flicksta.storages.AvatarStorage(),
                upload_to="",
            ),
        ),
    ]
