name: Flicksta Testing
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: development
      SECRET_KEY: secret_key
      ENCRYPT_KEY: mKJKI2CP4Nta3OmVMAV9aW6MOH43VHxaCfPGWdHg6R4=

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python manage.py test
